import { ActiveBlocker, CollaborationWindow, ExamplePreset, HandoffItem, OfficePresence, TimelineEvent } from './types';

export const EXAMPLE_PRESETS: ExamplePreset[] = [
  {
    id: 'marketing',
    name: 'Marketing Campaign Launch',
    team: 'Global Brand & Growth',
    from: 'London (Emma / James)',
    to: 'New York (Michael / Sarah)',
    workDescription: 'Completed global product campaign deck, drafted social ad copy variants, and finalized visual assets.',
    blockerDescription: 'Waiting for New York finance & leadership to sign off on the supplementary Q4 ad spend budget ($45,000).',
    nextDescription: 'Michael should review and approve the ad spend budget so Sarah can deliver final deck to client.',
    accomplished: 'Finished the campaign presentation and updated the social media graphics.',
    blocked: 'Waiting for the New York team to approve the final campaign budget.',
    nextAction: 'Michael should review the budget and send the presentation to the client.',
  },
  {
    id: 'consulting',
    name: 'Client Market Strategy',
    team: 'Management Consulting',
    from: 'New York (David / Sarah)',
    to: 'London (Emma / Olivia)',
    workDescription: 'Synthesized North American competitor landscape and prepared slides 1 through 15 with TAM calculations.',
    blockerDescription: 'European benchmarks and market size numbers are needed from London associates.',
    nextDescription: 'Emma should append European market metrics and complete the executive recommendation slides.',
    accomplished: 'Completed the market analysis and updated the first 15 slides.',
    blocked: 'Waiting for the London team to provide the latest European market numbers.',
    nextAction: 'Emma should add the numbers and complete the final recommendations slide.',
  },
  {
    id: 'sales',
    name: 'Enterprise Client Proposal',
    team: 'Enterprise Sales',
    from: 'London (Daniel)',
    to: 'New York (Michael)',
    workDescription: 'Finalized MSA scope, drafted security tier questionnaire responses, and loaded standard discount tiers.',
    blockerDescription: 'Custom multi-region discounting requires VP Sales sign-off before morning delivery.',
    nextDescription: 'Sales Director in New York must confirm custom enterprise discount and schedule signature call.',
    accomplished: 'Completed the client proposal and incorporated the latest product information.',
    blocked: 'Final pricing still needs approval.',
    nextAction: 'The New York sales manager should approve pricing and send the proposal tomorrow morning.',
  },
  {
    id: 'design',
    name: 'Product Design & Web Redesign',
    team: 'Product Experience',
    from: 'Tokyo (Ken / Mei)',
    to: 'London (Olivia / Sarah)',
    workDescription: 'Completed high-fidelity mobile & desktop homepage responsive layouts with interactive component states in Figma.',
    blockerDescription: 'Copywriting team needs to confirm approved legal disclosure and final hero taglines.',
    nextDescription: 'Sarah should paste approved marketing copy and export ready-for-engineering review bundle.',
    accomplished: 'Finished the homepage and updated the new visual style across the presentation.',
    blocked: 'Waiting for the marketing team to confirm the final wording.',
    nextAction: 'Sarah should add the approved wording and send the design for review.',
  },
  {
    id: 'finance',
    name: 'Monthly Operating & Revenue Report',
    team: 'Financial Planning & Analysis',
    from: 'New York (Sarah / David)',
    to: 'London (James / Daniel)',
    workDescription: 'Consolidated North American revenue streams, churn rates, and revised forecast graphs into board deck.',
    blockerDescription: 'Awaiting London shared-services to verify two international tax expense adjustments.',
    nextDescription: 'James should input the verified VAT/expense lines and circulate the consolidated report to executive team.',
    accomplished: 'Completed the monthly sales report and updated the revenue charts.',
    blocked: 'Waiting for the London office to confirm two expense numbers.',
    nextAction: 'James should add the final numbers and send the report to management.',
  },
];

export const INITIAL_OFFICES: OfficePresence[] = [
  {
    id: 'ny',
    city: 'New York',
    code: 'NYC',
    timezone: 'America/New_York',
    utcOffset: -4,
    workHours: '9:00 AM – 6:00 PM EDT',
    isCurrentlyWorkHours: true,
    members: [
      {
        id: 'ny-1',
        name: 'Sarah Chen',
        role: 'Client Strategy Lead',
        city: 'New York',
        avatar: 'SC',
        status: 'working',
        statusText: 'Reviewing deck slides 19–22',
        timeRemaining: '00:23:41',
        currentTask: 'Preparing Baton pass for Tokyo/London',
      },
      {
        id: 'ny-2',
        name: 'Michael Vance',
        role: 'VP Commercial & Budget',
        city: 'New York',
        avatar: 'MV',
        status: 'available',
        statusText: 'Available for pricing approvals',
        currentTask: 'Reviewing enterprise proposals',
      },
      {
        id: 'ny-3',
        name: 'Emma Hayes',
        role: 'Marketing Associate',
        city: 'New York',
        avatar: 'EH',
        status: 'meeting',
        statusText: 'Client alignment sync (until 11:30 AM)',
        currentTask: 'Campaign creative review',
      },
      {
        id: 'ny-4',
        name: 'David Ortiz',
        role: 'Financial Analyst',
        city: 'New York',
        avatar: 'DO',
        status: 'offline',
        statusText: 'Offline — starts 9:00 AM EDT',
      },
    ],
  },
  {
    id: 'ldn',
    city: 'London',
    code: 'LDN',
    timezone: 'Europe/London',
    utcOffset: 1,
    workHours: '9:00 AM – 5:30 PM BST',
    isCurrentlyWorkHours: true,
    members: [
      {
        id: 'ldn-1',
        name: 'James Wilson',
        role: 'Senior Brand Strategist',
        city: 'London',
        avatar: 'JW',
        status: 'working',
        statusText: 'Finalizing slides 1–18',
        timeRemaining: '01:45:10',
        currentTask: 'Updating campaign graphics',
      },
      {
        id: 'ldn-2',
        name: 'Olivia Sterling',
        role: 'Operations Lead',
        city: 'London',
        avatar: 'OS',
        status: 'working',
        statusText: 'Consolidating European metrics',
        currentTask: 'Ready to receive handoff',
      },
      {
        id: 'ldn-3',
        name: 'Daniel Croft',
        role: 'Client Partner',
        city: 'London',
        avatar: 'DC',
        status: 'meeting',
        statusText: 'Quick lunch / break until 2:00 PM',
      },
    ],
  },
  {
    id: 'tky',
    city: 'Tokyo',
    code: 'TYO',
    timezone: 'Asia/Tokyo',
    utcOffset: 9,
    workHours: '9:00 AM – 6:00 PM JST',
    isCurrentlyWorkHours: false,
    members: [
      {
        id: 'tky-1',
        name: 'Ken Takahashi',
        role: 'Principal UX Architect',
        city: 'Tokyo',
        avatar: 'KT',
        status: 'working',
        statusText: 'Design system tokens check',
        currentTask: 'Homepage redesign packaging',
      },
      {
        id: 'tky-2',
        name: 'Mei Tanaka',
        role: 'Product Specialist',
        city: 'Tokyo',
        avatar: 'MT',
        status: 'offline',
        statusText: 'Offline — logs in 9:00 AM JST',
      },
    ],
  },
];

export const INITIAL_HANDOFF_QUEUE: HandoffItem[] = [
  {
    id: 'hq-1',
    priority: 'high',
    project: 'Client Presentation Deck',
    title: 'Confirm final pricing & complete slides 19–22',
    owner: 'Sarah Chen',
    ownerLocation: 'New York',
    recipient: 'Michael Vance',
    recipientLocation: 'New York',
    status: 'pending',
    time: 'Due 1:00 PM',
    accomplished: 'Finished slides 1–18 of client presentation and updated campaign visuals.',
    blocked: 'Waiting for New York commercial team to confirm final pricing table.',
    nextAction: 'Michael to confirm tier 2 pricing; Sarah to insert and package final presentation.',
    sourceType: 'presentation',
  },
  {
    id: 'hq-2',
    priority: 'high',
    project: 'Q4 Marketing Campaign',
    title: 'Approve campaign budget ($45k spend)',
    owner: 'Michael Vance',
    ownerLocation: 'New York',
    recipient: 'Emma Hayes',
    recipientLocation: 'London',
    status: 'waiting',
    time: 'Urgent',
    accomplished: 'Completed campaign presentation deck and updated social media graphics.',
    blocked: 'Waiting for Michael in New York to approve final marketing budget.',
    nextAction: 'Michael should review budget and send presentation to the client.',
    sourceType: 'campaign',
  },
  {
    id: 'hq-3',
    priority: 'medium',
    project: 'Global Product Redesign',
    title: 'Review Tokyo homepage tokens & legal copy',
    owner: 'Emma Hayes',
    ownerLocation: 'London',
    recipient: 'Ken Takahashi',
    recipientLocation: 'Tokyo',
    status: 'pending',
    time: 'Before Tokyo AM',
    accomplished: 'Completed responsive desktop and mobile wireframes and interactive component state review.',
    blocked: 'Waiting for copy team to confirm final legal wording.',
    nextAction: 'Sarah/Emma should insert approved copy and clear package for engineering handoff.',
    sourceType: 'document',
  },
  {
    id: 'hq-4',
    priority: 'low',
    project: 'Monthly Operations Report',
    title: 'Verify European tax expense lines',
    owner: 'James Wilson',
    ownerLocation: 'London',
    recipient: 'David Ortiz',
    recipientLocation: 'New York',
    status: 'waiting',
    time: 'End of Week',
    accomplished: 'Completed monthly sales consolidation and updated revenue comparison charts.',
    blocked: 'Waiting for London finance team to confirm two expense adjustments.',
    nextAction: 'James should add the final numbers and distribute the report to leadership.',
    sourceType: 'financial',
  },
];

export const INITIAL_BLOCKERS: ActiveBlocker[] = [
  {
    id: 'blk-1',
    project: 'Client Presentation Deck',
    waitingOn: 'Michael Vance',
    waitingOnRole: 'VP Commercial & Pricing',
    waitingOnLocation: 'New York (EDT)',
    waitingOnStatus: 'available',
    need: 'Final tier 2 enterprise pricing numbers',
    urgency: 'critical',
    sinceTime: '1 hr 15 min ago',
    unblockActionHint: 'Michael is online now — 1-click ping will request instant pricing sign-off.',
  },
  {
    id: 'blk-2',
    project: 'Q4 Marketing Campaign',
    waitingOn: 'Emma Hayes',
    waitingOnRole: 'Marketing Associate',
    waitingOnLocation: 'London (BST)',
    waitingOnStatus: 'meeting',
    need: 'Final campaign headline & disclaimer wording',
    urgency: 'critical',
    sinceTime: '45 min ago',
    unblockActionHint: 'Emma is currently in a sync ending at 11:30 AM EDT. Baton queued the request.',
  },
  {
    id: 'blk-3',
    project: 'Monthly Operating Report',
    waitingOn: 'London Finance Team',
    waitingOnRole: 'FP&A European Desk',
    waitingOnLocation: 'London (BST)',
    waitingOnStatus: 'offline',
    need: 'Confirmation on two VAT expense line items',
    urgency: 'moderate',
    sinceTime: '3 hrs ago',
    unblockActionHint: 'London desk logs on in ~5 hours. Baton scheduled automated morning handoff brief.',
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'tl-1',
    project: 'Client Presentation Deck',
    author: 'Sarah Chen',
    authorLocation: 'New York',
    authorRole: 'Client Strategy Lead',
    type: 'handoff',
    content: 'Completed slides 1–18 and updated key campaign visuals. Packaging ready for review.',
    timestamp: 'Today — 4:45 PM EDT',
    badgeText: 'Baton Passed',
  },
  {
    id: 'tl-2',
    project: 'Client Presentation Deck',
    author: 'Michael Vance',
    authorLocation: 'New York',
    authorRole: 'VP Commercial',
    type: 'blocker',
    content: 'Waiting for final enterprise pricing table confirmation from London leadership.',
    timestamp: 'Today — 4:20 PM EDT',
    badgeText: 'Blocker Logged',
  },
  {
    id: 'tl-3',
    project: 'Market Strategy Deck',
    author: 'James Wilson',
    authorLocation: 'London',
    authorRole: 'Senior Brand Strategist',
    type: 'accomplished',
    content: 'Updated European market research and appended regional competitive landscape.',
    timestamp: 'Today — 2:15 PM BST',
    badgeText: 'Delivered',
  },
  {
    id: 'tl-4',
    project: 'Global Product Redesign',
    author: 'Emma Hayes',
    authorLocation: 'London',
    authorRole: 'Marketing Associate',
    type: 'decision',
    content: 'Team agreed to align Tokyo design tokens with European design system for consistent rollout.',
    timestamp: 'Yesterday — 5:30 PM BST',
    badgeText: 'Team Decision',
  },
  {
    id: 'tl-5',
    project: 'Client Presentation Deck',
    author: 'Ken Takahashi',
    authorLocation: 'Tokyo',
    authorRole: 'Principal UX Architect',
    type: 'accomplished',
    content: 'Completed initial deck design foundations and typography scales.',
    timestamp: 'Yesterday — 10:15 AM JST',
    badgeText: 'Initial Draft',
  },
];

export const COLLABORATION_WINDOWS: CollaborationWindow[] = [
  {
    pair: 'New York ↔ London',
    fromCity: 'New York (EDT)',
    toCity: 'London (BST)',
    windowLabel: 'Prime Overlap: 10:00 AM – 1:00 PM EDT (3:00 PM – 6:00 PM BST)',
    hoursOverlap: 3.5,
    bestWindow: '10 AM – 12 PM New York',
    note: 'Ideal window for live verbal baton handoffs and urgent blocker resolution.',
  },
  {
    pair: 'London ↔ Tokyo',
    fromCity: 'London (BST)',
    toCity: 'Tokyo (JST)',
    windowLabel: 'Morning Overlap: 7:00 AM – 9:30 AM BST (3:00 PM – 5:30 PM JST)',
    hoursOverlap: 2.5,
    bestWindow: '7 AM – 9 AM London',
    note: 'Best for London team to receive the baton fresh from Tokyo’s finished day.',
  },
  {
    pair: 'Tokyo ↔ New York',
    fromCity: 'Tokyo (JST)',
    toCity: 'New York (EDT)',
    windowLabel: 'Asynchronous Relay (13 hr shift difference)',
    hoursOverlap: 1.0,
    bestWindow: '8 PM – 9 PM New York (9 AM – 10 AM Tokyo)',
    note: 'Pure relay handoff: New York hands off as their workday closes, Tokyo picks up in morning.',
  },
];
